server:
  port: 11410

#数据库配置
spring:
  application:
    name: database
  datasource:
    url: jdbc:mysql://databaseserver:3306/cuitrwx?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: cuit123.


mybatis:
    configuration:
        map-underscore-to-camel-case: true
    type-aliases-package: cn.cuitrwx.database.dao   
logging:
  level: 
    cn:  DEBUG


eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:11400/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html#/

