server:
    port: 11410

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver1:11400/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    
spring:
  application:
    name: database