server:
    port: 11410                
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:11400/eureka/, http://eurekaserver1:11400/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    
spring:
  application:
    name: database
  datasource:
    url: jdbc:mysql://databaseserver.148:3306/cuitrwx?userSSL=false
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver
