

server:  
    port: 11443
      
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:11400/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true