server:
    port: 11400

eureka:
  server:
    enable-self-preservation: false

  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  instance:
    hostname: eurekaserver1
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    
spring:
  application:
    name: eureka