server:
    port: 11400

eureka:
  server:
    enable-self-preservation: false

  client:
    service-url:
      defaultZone: http://eurekaserver:11400/eureka/,http://eurekaserver1:11400/eureka/

  instance:
    hostname: eurekaserver
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    
spring:
  application:
    name: eureka